<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gejala_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gejala by id_gejala
     */
    function get_gejala($id_gejala)
    {
        return $this->db->get_where('gejala',array('id_gejala'=>$id_gejala))->row_array();
    }
        
    /*
     * Get all gejala
     */
    function get_all_gejala()
    {
        $this->db->order_by('id_gejala', 'desc');
        return $this->db->get('gejala')->result_array();
    }
        
    /*
     * function to add new gejala
     */
    function add_gejala($params)
    {
        $this->db->insert('gejala',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gejala
     */
    function update_gejala($id_gejala,$params)
    {
        $this->db->where('id_gejala',$id_gejala);
        return $this->db->update('gejala',$params);
    }
    
    /*
     * function to delete gejala
     */
    function delete_gejala($id_gejala)
    {
        return $this->db->delete('gejala',array('id_gejala'=>$id_gejala));
    }
}
