<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengetahuan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengetahuan by id_pengetahuan
     */
    function get_pengetahuan($id_pengetahuan)
    {
        return $this->db->get_where('pengetahuan',array('id_pengetahuan'=>$id_pengetahuan))->row_array();
    }
        
    /*
     * Get all pengetahuan
     */
    function get_all_pengetahuan()
    {
        $this->db->order_by('id_pengetahuan', 'desc');
        return $this->db->get('pengetahuan')->result_array();
    }
        
    /*
     * function to add new pengetahuan
     */
    function add_pengetahuan($params)
    {
        $this->db->insert('pengetahuan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengetahuan
     */
    function update_pengetahuan($id_pengetahuan,$params)
    {
        $this->db->where('id_pengetahuan',$id_pengetahuan);
        return $this->db->update('pengetahuan',$params);
    }
    
    /*
     * function to delete pengetahuan
     */
    function delete_pengetahuan($id_pengetahuan)
    {
        return $this->db->delete('pengetahuan',array('id_pengetahuan'=>$id_pengetahuan));
    }
}
